[package]
name = ""
version = "0.0.1"
authors = ["First Last <user@email>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = ""
readme = "README.md"
keywords = []
categories = []
repository = ""
publish = false # You should at least look at this file before you publish

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
